### ISSUE TITLE
[BUG] DataPanel.from_huggingface does not work

### ISSUE THREAD

**Issue by jessevig** [robustness-gym/meerkat#201]
**Describe the bug**
DataPanel.from_huggingface does not work

**To Reproduce**

import meerkat as mk
mk.DataPanel.from_huggingface('boolq')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/meerkat-test/lib/python3.8/site-packages/meerkat/datapanel.py", line 342, in from_huggingface
    return dict(
  File "/opt/anaconda3/envs/meerkat-test/lib/python3.8/site-packages/meerkat/datapanel.py", line 344, in <lambda>
    lambda t: (t[0], cls(t[1])),
  File "/opt/anaconda3/envs/meerkat-test/lib/python3.8/site-packages/meerkat/datapanel.py", line 78, in __init__
    self.data = data
  File "/opt/anaconda3/envs/meerkat-test/lib/python3.8/site-packages/meerkat/datapanel.py", line 152, in data
    self._set_data(value)
  File "/opt/anaconda3/envs/meerkat-test/lib/python3.8/site-packages/meerkat/datapanel.py", line 146, in _set_data
    raise ValueError(
ValueError: Cannot set DataPanel `data` to object of type <class 'datasets.arrow_dataset.Dataset'>.

**System Information**
 - OS: MacOs
 - meerkat-ml==0.2.3

**Comment by seyuboglu** [comment]
Should be fixed with #205
